---
title: Stackbit Ampersand Theme
baseURL: "/"
params:
  layout_style: list
  palette: red
  header:
    title: GATTO CURIOSO
    logo_img: "/images/Blue and Yellow Cat Animal & Pets Logo-1.png"
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links: []
    has_social: false
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
